tags:
- name: city
  description: cities temperatures API

paths:
# [GET] citynames
  /citynames:
    get:
      tags:
      - city
      summary: Retrieve all supported city names
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [GET] city/id
  /city?name=:
    get:
      tags:
      - city
      summary: Retrieve temperatures and sunrise/sunset time of a city
      parameters:
      - name: name
        in: query
        description: City name
        required: true
        type: string
      responses:
        200:
          description: 'OK'
        404:
          description: 'Data not found'
        500:
          description: 'Server Error'

# [GET] cities/id
  /cities?names=:
    get:
      tags:
      - city
      summary: Retrieve temperatures and sunrise/sunset time of multiple cities
      parameters:
      - name: names
        in: query
        description: City names separated by | symbol
        required: true
        type: string
      responses:
        200:
          description: 'OK'
        404:
          description: 'Data not found'
        500:
          description: 'Server Error'

schemes:
 - https
 - http
